# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa6937e9c760f8e98a7f40037fc4f1c08726fe22b01131c2c219cb5140c72636b7ff99d460350a13e324ca8e9cc4aa678273220b7a775dfa1547bfe07256ba65

test:
  secret_key_base: 30773f265f458a6a23df0fb211d24dc777bbfdc0c2d81b933266166d30a0b02ad8d5e3eec9313c08a6d9dd1246f5ea28586efbd7a421e38d31e1b1591362d92a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
